### ISSUE TITLE
Source of con_init function?

### ISSUE THREAD

**Issue by mistydemeo** [cyberwarriorx/pseudosaturn#3]
I'm trying to build pseudosaturn from source, but ran into an issue because of an "undefined reference to `con_init`" on line 462 of main.c. It looks like the usage of `con_init ` was added in https://github.com/cyberwarriorx/pseudosaturn/commit/a006375f52e2d514cb439d4f00f43bb850fef173, but I don't see where the function itself comes from.

**Comment by cyberwarriorx** [comment]
Fixed
